[manifest]
version = "1.0.0"
priority = 30

# SMODS.calculate_context()
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = ''''message','''
position = "before"
payload = ''''pre_func','''
match_indent = true
times = 3

# SMODS.calculate_context()
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''if key == 'message' then'''
position = "before"
payload = '''if key == 'pre_func' then
    effect.pre_func()
    return true
end'''
match_indent = true
times = 3